mybatis:
  configuration:
    database-id: mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
---
spring:
  profiles: mysql_dpl
  datasource:
    username: dev
    password: "QzpYRKEZUEkVsm/J9ttWeg=="
    url: jdbc:mysql://localhost:3306/market_test?autoReconnect=true&failOverReadOnly=false&&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
---
spring:
  profiles: mysql_hiki
  datasource:
    username: root
    password: aneureka
    url: jdbc:mysql://localhost:3306/nju_backpack_market?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
