spring:
  datasource:
    username: dev
    password: "QzpYRKEZUEkVsm/J9ttWeg=="
    url: jdbc:mysql://localhost:3306/market_test
    driver-class-name: com.mysql.jdbc.Driver
upload:
  image:
    location: /var/site/static/image
  video:
    location: /var/site/static/video
alipay:
  return-url: https://clevelandalto.site:8080/payments/alipay/return
  notify-url: https://clevelandalto.site:8080/payments/alipay/notify
