spring:
  datasource:
    username: dev
    password: "QzpYRKEZUEkVsm/J9ttWeg=="
    url: jdbc:mysql://123.206.119.37:3306/market_test
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      location: D:/tmp/
upload:
  image:
    location: D:/image
  video:
    location: D:/image
