spring:
  datasource:
    username: dev
    password: "{{enc:67 58 88 68 -95 25 80 73 21 -78 111 -55 -10 -37 86 122"
    url: jdbc:mysql://123.206.119.37:3306/market_test
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      location: D:/tmp/
upload:
  image:
    location: D:/image
  video:
    location: D:/image
server:
  ssl:
    key-store:
    key-store-password: "67 58 88 68 -95 25 80 73 -102 9 37 -69 93 82 63 93"
