spring:
  profiles:
    active: dev_local
pagehelper: # configuration for PageHelper
  helper-dialect: mysql
  auto-dialect: "true"
  auto-runtime-dialect: "false"
  page-size-zero: "false"
  offset-as-page-num: "true"
  row-bounds-with-count: "true"
  support-methods-arguments: "false"
  close-conn: "false"
  reasonable: "true"
mybatis:
  type-aliases-package: cn.sansotta.market.domain.entity
