spring:
  datasource:
    username: root
    password: aneureka
    url: jdbc:mysql://localhost:3306/nju_backpack_market?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

