spring:
  profiles:
    active: dev_local
  jackson:
    property-naming-strategy: SNAKE_CASE
  http:
    multipart:
      resolve-lazily: true
      max-request-size: 50MB
      max-file-size: 50MB
  datasource:
    druid:
      test-while-idle: false
pagehelper: # configuration for PageHelper
  page-size-zero: "false"
  offset-as-page-num: "true"
  row-bounds-with-count: "true"
  support-methods-arguments: "false"
  reasonable: "true"
  auto-dialect: "true"
mybatis:
  type-aliases-package: cn.sansotta.market.domain.entity

