spring:
  profiles:
    active: dev_local
  data:
    rest:
      base-path: /api/v1
  jackson:
    property-naming-strategy: SNAKE_CASE
  http:
    multipart:
      resolve-lazily: true
      max-request-size: 10MB
      max-file-size: 50MB
pagehelper: # configuration for PageHelper
  page-size-zero: "false"
  offset-as-page-num: "true"
  row-bounds-with-count: "true"
  support-methods-arguments: "false"
  reasonable: "true"
  auto-dialect: "true"
mybatis:
  type-aliases-package: cn.sansotta.market.domain.entity

